import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const mulish = Mulish({
  subsets: ['latin'],
  variable: '--font-mulish',
})

export const metadata: Metadata = {
  title: "Spotbio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mulish.variable} font-mulish antialiased`}
      >
        {children}
        <Toaster richColors/>
      </body>
    </html>
  );
}
